# Generated by Django 3.2.8 on 2021-11-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211101_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_name',
            field=models.CharField(max_length=255),
        ),
    ]
