# Generated by Django 3.2.8 on 2021-11-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_keyword_keyword_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
