# Generated by Django 3.2.8 on 2021-11-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
